"""ly: adddd support of markdown

Revision ID: 17c417d64da4
Revises: 31169f516ff1
Create Date: 2015-12-20 17:27:27.463872

"""

# revision identifiers, used by Alembic.
revision = '17c417d64da4'
down_revision = '31169f516ff1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('description_html', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('about_me_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me_html')
    op.drop_column('conferences', 'description_html')
    ### end Alembic commands ###
