"""ly: complete user info

Revision ID: 31169f516ff1
Revises: bde2181a843
Create Date: 2015-12-20 10:52:36.190672

"""

# revision identifiers, used by Alembic.
revision = '31169f516ff1'
down_revision = 'bde2181a843'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('join_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'join_time')
    op.drop_column('users', 'address')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
